Quote branch
gorrelljd21/quotes-api pull request #5
Opened 2022-10-12 20:36 UTC by gorrelljd21

Completed for task  "Add a GraphQL Schema for Quotes API#237"

Created a schema for the quotes api through initializing gqlgen and ensured that by regenerating, the models and resolvers automagically updated.

2022-10-13 15:46 UTC, boggsey approved these changes
Good work! Now you'll need to write your resolvers!

2022-10-15 12:45 UTC, librairica commented on main.go
> +	r.Run("0.0.0.0:8081")
I had to change this to 8080 to run both your API servers
```suggestion
	r.Run("0.0.0.0:8080")
```

2022-10-15 12:50 UTC, librairica requested changes
When I tried to test your code, I ran into some port in use errors, so I changed your rest api's port to 8080 and I could at least query in the GraphiQL explorer. I was getting empty strings back on all quote fields in GraphiQL, so I went ahead and checked the REST API in postman and it was also returning a random quote with empty fields. Is the db empty? It would be super helpful if you updated the description for this PR with some instructions for how to test.

2022-10-17 20:03 UTC, librairica approved these changes
Once I added your db values to my zsh, both queries worked!

2022-10-17 20:05 UTC, merged